#!/bin/bash
# Script para agregar D1 binding a Cloudflare Pages

echo "Para agregar el binding D1 a tu proyecto Cloudflare Pages:"
echo ""
echo "1. Ve al dashboard de Cloudflare Pages:"
echo "   https://dash.cloudflare.com/"
echo ""
echo "2. Selecciona tu proyecto 'smart-homes'"
echo ""
echo "3. Ve a Settings > Functions > D1 database bindings"
echo ""
echo "4. Click en 'Add binding'"
echo ""
echo "5. Configura:"
echo "   Variable name: DB"
echo "   D1 database: smart-homes-production"
echo ""
echo "6. Click 'Save'"
echo ""
echo "O usa la API de Cloudflare:"
echo ""
echo "ACCOUNT_ID=\$(npx wrangler whoami | grep 'Account ID' | awk '{print \$3}')"
echo "PROJECT_NAME='smart-homes'"
echo "DATABASE_ID='c2818feb-c3b8-4ee0-b474-dc45afb55905'"
echo ""
echo "Binding configurado automáticamente en wrangler.jsonc"
echo "La próxima vez que hagas 'npm run deploy' se aplicará automáticamente"
